#' Capture and log messages
#'
#' @description `capture_local_messages()` is a wrapper function that returns
#' the output and messages when running a function.
#'
#' @param expr Function to wrap.
#'
#' @return A list containing two variables, `dat` and `msg`. `dat` contains the
#' output of the wrapped function, while `msg` contains a log of all messages
#' generated by the wrapped function.
#'
#' @noRd
capture_local_messages <- function(expr) {
  # Create a text connection to capture output
  temp <- textConnection("messages", "w", local = TRUE)
  sink(temp, type = "message")
  on.exit({
    sink(type = "message")
    close(temp)
  })

  # Run wrapped function
  result <- expr
  new_log <- ""

  # Save the captured messages
  if (exists("messages")) {
    new_log <- paste(messages, collapse = "\n")
    # Remove odd characters at start of each message - due to namespace issues?
    new_log <- gsub("\\\033..;|\\\033.", "", new_log)
  }

  list(
    dat = result,
    msg = new_log
  )
}

#' Upload custom result format
#'
#' @description `custom_result_format()` is a helper function for `mod_format()`
#' that parses custom result formats.
#'
#' @param .data Uploaded excel file
#'
#' @return Named list of variable names. List is composed of old variables, with
#' the new variables set as names. If no valid entries found, returns `NULL`.
#'
#' @noRd
upload_result_format <- function(.data) {
  in_dat <- .data$datapath

  message("Uploading custom result format...\n")
  col_result <- parse_format(in_dat, "Column Names")
  var_parameter <- parse_format(in_dat, "Parameters")
  var_unit <- parse_format(in_dat, "Units")
  var_qualifier <- parse_format(in_dat, "Qualifiers")
  var_activity <- parse_format(in_dat, "Activity Types")

  # Check - allow custom result format?
  all_val <- c(
    col_result, var_parameter, var_unit, var_qualifier, var_activity
  )
  if (is.null(all_val)) {
    stop("Blank file")
  }

  message("\nDone")
  list(
    col_name = col_result,
    param = var_parameter,
    param_unit = var_unit,
    qualifier = var_qualifier,
    activity = var_activity
  )
}

#' Upload custom site format
#'
#' @description `custom_site_format()` is a helper function for `mod_format()`
#' that parses custom site formats.
#'
#' @param .data Uploaded excel file
#'
#' @return Named list of column names. List is composed of old variables, with
#' the new variables set as names. If no valid entries found, returns `NULL`.
#'
#' @noRd
upload_site_format <- function(.data) {
  in_dat <- .data$datapath

  message("Uploading custom site format...\n")
  site_col <- parse_format(in_dat, "Column Names")

  # Check - allow custom result format?
  if (is.null(site_col)) {
    stop("Blank file")
  }

  message("\nDone")
  site_col
}

#' Upload custom format
#'
#' @description `parse_format()` uploads a sheet from the custom conversion
#' excel table and produces a named list containing variables to convert.
#'
#' @param .data Input excel file
#' @param sheet_name Sheet to read. Either a string (the name of a sheet), or an
#' integer (the position of the sheet).
#'
#' @return Named list of variable names. List is composed of old variables, with
#' the new variables as names. If no valid entries found, returns `NULL`.
#'
#' @noRd
parse_format <- function(.data, sheet_name) {
  msg <- paste0("\tGenerating conversion table for ", sheet_name, "... ")
  dat <- readxl::read_excel(
    .data,
    sheet = sheet_name,
    col_types = "text",
    na = c("NA", "na", "")
  ) |>
    dplyr::select("MassWateR", "Custom") |>
    dplyr::filter(
      !is.na(.data$MassWateR),
      !is.na(.data$Custom)
    )

  if (nrow(dat) == 0) {
    message(msg, "no data")
    return(NULL)
  }

  message(msg, "ok")
  out <- dat$Custom
  names(out) <- dat$MassWateR

  out
}

#' Upload non-MassWateR result data
#'
#' @description `upload_custom_results()` uploads an excel file containing
#' result data and formats it for MassWateR.
#'
#' @param dat Path to excel file
#' @param in_format String. Way the input data is formatted.
#' @param custom_format List containing the following variables: col_name,
#' param, param_unit, qualifier, activity. Each variable is a named list
#' containing old and new variable names.
#'
#' @return Dataframe that has been formatted for MassWateR
#'
#' @noRd
upload_custom_results <- function(dat, in_format, custom_format = NULL) {
  msg <- "Uploading result data..."
  dat <- readxl::read_excel(
    dat$datapath,
    na = c("NA", "na", "")
  ) |>
    dplyr::mutate_if(function(x) !lubridate::is.POSIXct(x), as.character)

  message(msg, " ok\n")

  if (in_format == "masswater") {
    dat <- wqformat::format_mwr_results(dat)
  } else if (in_format == "custom") {
    dat <- format_custom_results(dat, custom_format)
  } else {
    dat <- wqformat::format_results(dat, in_format, "masswater")
  }

  dat
}

#' Convert custom results to MassWateR format
#'
#' @description `format_custom_results()` converts input data from a custom
#' format to MassWateR by renaming columns and key variables.
#'
#' @param .data Dataframe
#' @param var_list List containing the following variables: col_name, param,
#' param_unit, qualifier, activity. Each variable is a named list containing old
#' and new variable names.
#'
#' @return Updated dataframe that has been formatted for MassWateR
#'
#' @noRd
format_custom_results <- function(.data, var_list) {
  dat <- .data

  message("Reformatting data...")

  # Update columns
  col_names <- var_list$col_name
  if (!is.null(col_names)) {
    message("\tRenaming columns")
    dat <- dat |>
      wqformat::rename_col(col_names, names(col_names))
  }

  all_col <- c(
    "Monitoring Location ID", "Activity Type", "Activity Start Date",
    "Activity Start Time", "Activity Depth/Height Measure",
    "Activity Depth/Height Unit", "Activity Relative Depth Name",
    "Characteristic Name", "Result Value", "Result Unit",
    "Quantitation Limit", "QC Reference Value", "Result Measure Qualifier",
    "Result Attribute", "Sample Collection Method ID", "Project ID",
    "Local Record ID", "Result Comment"
  )
  missing_col <- setdiff(all_col, colnames(dat))
  if (length(missing_col) > 0) {
    dat[missing_col] <- NA
    message("\tAdded ", length(missing_col), " missing columns")
  }

  # Update variables
  dat <- dat |>
    try_rename("Characteristic Name", var_list$param) |>
    try_rename("Result Unit", var_list$param_unit) |>
    try_rename("Result Measure Qualifier", var_list$qualifier) |>
    try_rename("Activity Type", var_list$activity) |>
    wqformat::format_mwr_results()
}

#' Upload non-MassWateR site metadata
#'
#' @description `upload_custom_sites()` uploads an excel file containing site
#' metadata and formats it for MassWateR.
#'
#' @param dat Path to excel file
#' @param in_format String. Way the input data is formatted.
#' @param custom_format Named list containing old and new column names.
#'
#' @return Dataframe that has been formatted for MassWateR
#'
#' @noRd
upload_custom_sites <- function(dat, in_format, custom_format = NULL) {
  msg <- "Uploading site metadata..."
  dat <- readxl::read_excel(
    dat$datapath,
    na = c("NA", "na", "")
  ) |>
    dplyr::mutate_if(function(x) !lubridate::is.POSIXct(x), as.character)

  message(msg, " ok\n")

  if (in_format == "custom") {
    dat <- wqformat::rename_col(dat, custom_format, names(custom_format))
    message("Renaming columns... ok\n\nDone")
  } else if (in_format != "masswater") {
    dat <- wqformat::format_sites(dat, in_format, "masswater")
  }

  dat
}

#' Rename variables in column
#'
#' @description `try_rename()` is a helper function for `convert_results()`
#' that renames the variables in a column.
#'
#' @param .data Input dataframe
#' @param col_name Column name.
#' @param var_names Named vector. Vector should consist of old variable names,
#' with vector names set to equivalent new variable name.
#'
#' @return Updated dataframe. If `var_names` is `NA` or `NULL`, the original
#' dataframe is returned.
#'
#' @noRd
try_rename <- function(.data, col_name, var_names) {
  if (is.null(var_names)) {
    return(.data)
  }

  message("\tRenamed ", col_name, " variables")

  new_var <- names(var_names)
  old_var <- unname(var_names)

  .data |>
    wqformat::update_var(col_name, old_var, new_var)
}
